module ALU(
	A,
	B,
	op,
	F,
	R,
	D);

	//---Ports declearation: generated by Robei---
	input [7:0] A;
	input [7:0] B;
	input [3:0] op;
	input F;
	output [7:0] R;
	output D;

	wire [7:0] A;
	wire [7:0] B;
	wire [3:0] op;
	wire F;
	reg [7:0] R;
	reg D;

	//----Code starts here: integrated by Robei-----
	always @ ( A or B or op or F )
	begin
		case (op)
		3'b000: {D,R}=A&B;
		3'b001: {D,R}=A | B;
		3'b010: {D,R}=~ A;
		3'b011: {D,R}=A^B;
		3'b100: {D,R}=A+B;
		3'b101: {D,R}=A+B+F;
		3'b110: {D,R}=A-B;
		3'b111: {D,R}=A-B-F;
		default:{D,R}=A&B;
		endcase
	end
endmodule    //ALU

