module counter(
	clock,
	reset,
	enable,
	count);

	//---Ports declearation: generated by Robei---
	input clock;
	input reset;
	input enable;
	output [3:0] count;

	wire clock;
	wire reset;
	wire enable;
	reg [3:0] count;

	//----Code starts here: integrated by Robei-----
	always @ ( posedge clock )
	begin
		if ( reset == 1)
		begin
			count <= 0;
		end
		else if ( enable == 1)
		begin
			count <= count + 1;
		end
	end
	
	
endmodule    //counter

