module decoder(
	din,
	en,
	out);

	//---Ports declearation: generated by Robei---
	input [2:0] din;
	input en;
	output [7:0] out;

	wire [2:0] din;
	wire en;
	wire [7:0] out;

	//----Code starts here: integrated by Robei-----
	assign out = ( en ) ? ( din << 1 ) : 8'b0;
	
	
	
endmodule    //decoder

