module encoder(
	x,
	en,
	y);

	//---Ports declearation: generated by Robei---
	input [7:0] x;
	input en;
	output [2:0] y;

	wire [7:0] x;
	wire en;
	reg [2:0] y;

	//----Code starts here: integrated by Robei-----
	always @ ( en or x )
	begin
		if ( en )
		begin
			case ( x )
			8'b00000001 : y = 3'b000;
			8'b00000010 : y = 3'b001;
			8'b00000100 : y = 3'b010;
			8'b00001000 : y = 3'b011;
			8'b00010000 : y = 3'b100;
			8'b00100000 : y = 3'b101;
			8'b01000000 : y = 3'b110;
			8'b10000000 : y = 3'b111;
			default : y = 3'b000;
			endcase
		end
	end	 
		
	
	
endmodule    //encoder

